### PR TITLE
Add to the `render_callback`

### PR DESCRIPTION
**Pull request by kienstra**
* Adds another query to the `render_callback` for candidates to work with
* Adds more coding style issues for candidates to find
* Updates the Composer package `mockery/mockery` to the latest

### CODE REVIEW

**Comment by sboisvert** [comment]
@kienstra I made a few changes, what are your thoughts on this? Can we incorporate this? We'll need to update the scoring chart. And also, I think we'll want to nuke the branch to start from scratch so there's no history in this repo.

**Comment by kienstra** [comment]
Hi @sboisvert,
Nice, https://github.com/xwp-hiring/coding-challenge/pull/6/commits/0cc453ae6b2d89446a2c2779097179a6bd23c559 looks good. Good idea to start from scratch so this history isn't here.

Once you merge this, maybe one of us could force-push to the `develop` branch a single commit, so there's no commit history anymore.

**Comment by sboisvert** [comment]
k, merged it! Do you want to do a force push when you have time?

**Comment by kienstra** [comment]
>k, merged it! Do you want to do a force push when you have time?

Sure, I will!

**Comment by kienstra** [comment]
Hi @sboisvert, 
I just did the force push to the `develop` branch, so everything is in a single commit now.

**Pull request merged**
